services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'db_usuarios'
      MYSQL_USER: 'luis'
      MYSQL_PASSWORD: '1234'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-ui
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: